### ISSUE TITLE
Tab keys are inserting a character when using gecko driver

### ISSUE THREAD

**Issue by jonnycornwell** [theintern/leadfoot#110] opened 2017-05-26 13:08 UTC
Leadfoot: 1.7.4
Selenium: 3.4.0
Firefox: 53.0.3 (64)
Geckodriver: 0.16.0-x63
Intern (probably irrelevant): 3.4.4

I would note that it works with FF46, and selenium 2.53.1

## Repro (excuse the typescript)

        await command.get('data:text/html;charset=utf-8,' + encodeURIComponent("<!DOCTYPE html><input id='input'/>"));

        let element = await command.findById("input");

        await element.type("username");
        await element.session.pressKeys(Keys.TAB);
        await element.session.pressKeys(Keys.NULL);

## Result
![image](https://cloud.githubusercontent.com/assets/15254526/26495756/b8b16282-421c-11e7-9af4-91b4f18d2571.png)

**Comment by jonnycornwell** [comment] 2017-07-13 08:30
Sorry to be impatient but I am just wondering if this has been looked at?

Thanks, J

**Comment by jason0x43** [comment] 2017-07-13 15:57
No problem, we've just been bogged down a bit working the upcoming version. :)

It looks like the problem is related to `pressKeys`. This works as expected (at least, it tabs out of an input):

```ts
await element.type('username');
await element.type(Keys.TAB);
```

Using `pressKeys`, on the other hand, inserts a tab character. The problem is that pressKeys is using simulated key events with geckodriver, and the browser isn't handling our simulated tab event in the way we'd expect.

**Comment by jason0x43** [comment] 2020-01-15 19:28
Closing in favor of theintern/intern#1038

**Closed by jason0x43** 2020-01-15 19:28 UTC
