### ISSUE TITLE
Element API is not chainable like Session

### ISSUE THREAD

**Issue by xzyfer** [theintern/leadfoot#33] opened 2015-03-16 06:01 UTC
Given the follow example

```js
remote.get('http://foo.com')
  .findByCssSelector('input[id=MightNotBePresent]')
    .then(function (element) {
      return element
        .click()
        .type('test');
    }, function () {
      // This element is only rendered under certain conditions
      // if it's not on the page carry on, everything is fine.
    })
    .end();
```

Unexpectedly results in the following error on line 6

>TypeError: Object #<Promise> has no method 'type'

However flattening this out by removing the `then` works fine

```js
remote.get('http://foo.com')
  .findByCssSelector('input[id=MightNotBePresent]')
    .click()
    .type('test');
    .end();
```

This however expects the element will always be on the page which is not case.

**Comment by xzyfer** [comment] 2015-03-16 06:03
Using a local ChromeDriver 2.14.313457.

```
chromedriver --port=4444 --url-base=wd/hub
```

leadfoot@1.2.1 via intern@2.2.2

**Comment by xzyfer** [comment] 2015-03-16 06:09
It's worth noting I have tried working directly with the session via the `this` parameter.
However this causes code to not wait for `then` to fully resolve.

Given code like below the form is _sometimes_ submitted before the input is typed into.

```
remote.get('http://foo.com')
  .findByCssSelector('input[id=MightNotBePresent]')
    .then(function (element) {
      this
        .click()
        .type('test');
    }, function () {
      // This element is only rendered under certain conditions
      // if it's not on the page carry on, everything is fine.
    })
    .end()
  .findByCssSelector('input[type=submit]')
    .click()
;
```

**Comment by jason0x43** [comment] 2015-03-16 13:03
This is expected behavior. As described in the Leadfoot API documentation, methods in the Element API return Promises while methods in the Command API (which is what you're using when chaining on `remote`) return Commands. This means that values returned from Element calls are only going to support the standard Promise methods.

Since the find call will have set the context if the element was found, in your success callback you can just start a chain from `this.parent`. (As the [Command](https://theintern.github.io/leadfoot/Command.html) documentation points out, trying to return `this` or a `this`-based chain from a Command callback will deadlock the command.)

```js
remote.get('http://foo.com')
  .findByCssSelector('input[id=MightNotBePresent]')
    .then(function () {
      return this.parent
        .click()
        .type('test');
    }, function () {
      // This element is only rendered under certain conditions
      // if it's not on the page carry on, everything is fine.
    })
    .end();
```

**Comment by xzyfer** [comment] 2015-03-16 13:35
>As described in the Leadfoot API documentation, methods in the Element API return Promises while methods in the Command API [...] return Commands

I believe this is the crux the issue. Take for example the `clearValue()` method both the [Command](http://theintern.github.io/leadfoot/Command.html#clearValue) and [Element](http://theintern.github.io/leadfoot/Element.html#clearValue) APIs claim to return `Promise.<void>`. 

However the `clearValue()` is chainable outside `then()` but not inside.

```js
remote.get('http://foo.com')
  .findByCssSelector('input[id=MightNotBePresent]')
    .then(function () {
      return this
        .clearValue()
        .click();
    }, function () {
      // This element is only rendered under certain conditions
      // if it's not on the page carry on, everything is fine.
    })
    .end();
```

Results in the following error `TypeError: Object #<Promise> has no method 'click'`, where as the follow executes fine.

```js
remote.get('http://foo.com')
  .findByCssSelector('input[id=MightNotBePresent]')
    .clearValue()
    .click();
    .end();
```

I accept this may be intentional however I believe the docs to be misleading in this regard.

**Comment by xzyfer** [comment] 2015-03-16 13:52
You're `this.parent` solution works and it much cleaner than the `then()` nesting I had to do to get things working.

Even though I can reason about why it works, I do not think it's clear from the documentation. From the `Command.then()` docs

>The `context (this)` of the callback is set to the Command object, rather than being undefined.

This gave me the impression `this` was the same Command object, not a new Command context that references the old via `.parent`. Although the nature of `parent` is well described you have to know look for it in the first place.

***

I'm not what, if any, resolution exists for this issue. It's just that I found the API counter intuitive, and the documentation unhelpful or misleading. 

It would be great to have something non-trivial in the example repo for reference since there are scarcely few references on how to use leadfoot beyond the main intern docs.

**Comment by csnover** [comment] 2015-04-04 00:52
Sorry about the return type documentation problem, this is due to a limitation of jsdoc and is noted in bold at the top of the Element documentation. If you have suggestions on how to improve this please let us know or send a PR with documentation improvements that you think would help.

As far as examples go, we would love to have more examples but we’re severely resource constrained, so rely on the community to help us with these so we can push forward core development in the small amount of time we have available.

Since I am not sure that there is any immediate actionable item here, and the problem described in the OP is due to a coding error, I am going to close this ticket for now but please let me know if it should be reopened with any particular next steps. Thanks!

**Closed by csnover** 2015-04-04 00:52 UTC
